apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: frontend-wtrs
  namespace: app
spec:
  weighted:
    services:
      - name: frontend-stable
        port: 8080
        weight: 100
      - name: frontend-canary
        port: 8080
        weight: 0
