name: Backend Secure Pipeline

on:
  push:
    paths:
      - "devops-system-design-challenge/apps/backend/**"
      - "devops-system-design-challenge/infra/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/reusable-app-pipeline.yml"
  pull_request:
    paths:
      - "devops-system-design-challenge/apps/backend/**"
      - "devops-system-design-challenge/infra/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/reusable-app-pipeline.yml"

jobs:
  backend:
    uses: ./.github/workflows/reusable-app-pipeline.yml
    with:
      app_name: backend
      app_path: devops-system-design-challenge/apps/backend
      dockerfile_path: devops-system-design-challenge/apps/backend/Dockerfile
      codeql_language: go
      dependency_file: devops-system-design-challenge/apps/backend/go.mod
      deploy_name: backend
      container_name: backend
      route_prefix: /backend
    secrets: inherit
