name: Backend Secure Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "devsecops/apps/backend/**"
      - "devsecops/infra/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/reusable-app-pipeline.yml"
  pull_request:
    paths:
      - "devsecops/apps/backend/**"
      - "devsecops/infra/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/reusable-app-pipeline.yml"

permissions:
  contents: read
  security-events: write
  packages: write
  id-token: write
  attestations: write

jobs:
  backend:
    uses: ./.github/workflows/reusable-app-pipeline.yml
    with:
      app_name: backend
      app_path: devsecops/apps/backend
      dockerfile_path: devsecops/apps/backend/Dockerfile
      codeql_language: go
      dependency_file: devsecops/apps/backend/go.mod
      deploy_name: backend
      container_name: backend
      route_prefix: /backend
    secrets: inherit
