name: Frontend Secure Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "devsecops/apps/frontend/**"
      - "devsecops/infra/**"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/reusable-app-pipeline.yml"
  pull_request:
    paths:
      - "devsecops/apps/frontend/**"
      - "devsecops/infra/**"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/reusable-app-pipeline.yml"

permissions:
  contents: read
  security-events: write
  packages: write
  id-token: write
  attestations: write

jobs:
  frontend:
    uses: ./.github/workflows/reusable-app-pipeline.yml
    with:
      app_name: frontend
      app_path: devsecops/apps/frontend
      dockerfile_path: devsecops/apps/frontend/Dockerfile
      codeql_language: python
      dependency_file: devsecops/apps/frontend/src/frontend/requirements.txt
      deploy_name: frontend
      container_name: frontend
      route_prefix: /frontend
    secrets: inherit
